name: prefs
description: Flutter plugin for reading & writting key-value data effectively(memory cache) and persistently(disk).
version: 0.0.1
author: walfud
homepage: https://github.com/walfud/flutter_prefs

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.3